import { Week, Game, Team } from "@/types";

const teams: Record<string, Team> = {
  KC: {
    id: "KC",
    name: "Kansas City Chiefs",
    abbr: "KC",
    color: "#E31828",
    wins: 11,
    losses: 3,
  },
  BUF: {
    id: "BUF",
    name: "Buffalo Bills",
    abbr: "BUF",
    color: "#00338D",
    wins: 10,
    losses: 4,
  },
  SF: {
    id: "SF",
    name: "San Francisco 49ers",
    abbr: "SF",
    color: "#AA0000",
    wins: 10,
    losses: 4,
  },
  DAL: {
    id: "DAL",
    name: "Dallas Cowboys",
    abbr: "DAL",
    color: "#003594",
    wins: 9,
    losses: 5,
  },
  PHI: {
    id: "PHI",
    name: "Philadelphia Eagles",
    abbr: "PHI",
    color: "#004687",
    wins: 10,
    losses: 4,
  },
  DEN: {
    id: "DEN",
    name: "Denver Broncos",
    abbr: "DEN",
    color: "#FB4F14",
    wins: 8,
    losses: 6,
  },
  LV: {
    id: "LV",
    name: "Las Vegas Raiders",
    abbr: "LV",
    color: "#000000",
    wins: 6,
    losses: 8,
  },
  GB: {
    id: "GB",
    name: "Green Bay Packers",
    abbr: "GB",
    color: "#203731",
    wins: 7,
    losses: 7,
  },
};

export function getMockWeek(weekNumber: number): Week {
  const games: Game[] = [
    {
      id: "game-1",
      week: weekNumber,
      homeTeam: teams.KC,
      awayTeam: teams.BUF,
      homeScore: 24,
      awayScore: 17,
      status: "final",
      gameTime: "3:25 PM ET",
      homeMetrics: {
        epaOffensePercentile: 78,
        epaOffenseValue: 0.15,
        epaDefensePercentile: 82,
        epaDefenseValue: -0.18,
        passNeutralRate: 0.52,
        scoringDriveRateOffense: 0.38,
        scoringDriveRateDefense: 0.28,
        tdDriveRateOffense: 0.22,
        tdDriveRateDefense: 0.12,
        turnoverDriveRateOffense: 0.08,
        turnoverDriveRateDefense: 0.14,
        thirdDownEfficiencyOffense: 0.42,
        thirdDownEfficiencyDefense: 0.35,
        penaltiesOffensive: 5,
        penaltiesDefensive: 3,
        penaltiesCommittedCount: 5,
        penaltiesCommittedYards: 40,
        penaltiesForcedCount: 3,
        penaltiesForcedYards: 25,
        fgDriveRateOffense: 0.15,
        puntDriveRateOffense: 0.18,
        fgDriveRateDefense: 0.14,
        puntDriveRateDefense: 0.22,
        rankTdRate: 8,
        rankFgRate: 12,
        rankPuntRate: 15,
        rankTurnoverRate: 10,
      },
      awayMetrics: {
        epaOffensePercentile: 72,
        epaOffenseValue: 0.12,
        epaDefensePercentile: 75,
        epaDefenseValue: -0.15,
        passNeutralRate: 0.48,
        scoringDriveRateOffense: 0.32,
        scoringDriveRateDefense: 0.35,
        tdDriveRateOffense: 0.18,
        tdDriveRateDefense: 0.16,
        turnoverDriveRateOffense: 0.12,
        turnoverDriveRateDefense: 0.10,
        thirdDownEfficiencyOffense: 0.38,
        thirdDownEfficiencyDefense: 0.42,
        penaltiesOffensive: 6,
        penaltiesDefensive: 2,
        penaltiesCommittedCount: 6,
        penaltiesCommittedYards: 45,
        penaltiesForcedCount: 2,
        penaltiesForcedYards: 20,
        fgDriveRateOffense: 0.12,
        puntDriveRateOffense: 0.22,
        fgDriveRateDefense: 0.16,
        puntDriveRateDefense: 0.20,
        rankTdRate: 12,
        rankFgRate: 10,
        rankPuntRate: 18,
        rankTurnoverRate: 14,
      },
    },
    {
      id: "game-2",
      week: weekNumber,
      homeTeam: teams.SF,
      awayTeam: teams.DAL,
      homeScore: 28,
      awayScore: 21,
      status: "final",
      gameTime: "7:20 PM ET",
      homeMetrics: {
        epaOffensePercentile: 85,
        epaOffenseValue: 0.22,
        epaDefensePercentile: 88,
        epaDefenseValue: -0.20,
        passNeutralRate: 0.55,
        scoringDriveRateOffense: 0.45,
        scoringDriveRateDefense: 0.25,
        tdDriveRateOffense: 0.28,
        tdDriveRateDefense: 0.08,
        turnoverDriveRateOffense: 0.06,
        turnoverDriveRateDefense: 0.16,
        thirdDownEfficiencyOffense: 0.48,
        thirdDownEfficiencyDefense: 0.32,
        penaltiesOffensive: 4,
        penaltiesDefensive: 2,
      },
      awayMetrics: {
        epaOffensePercentile: 68,
        epaOffenseValue: 0.08,
        epaDefensePercentile: 65,
        epaDefenseValue: -0.10,
        passNeutralRate: 0.45,
        scoringDriveRateOffense: 0.28,
        scoringDriveRateDefense: 0.42,
        tdDriveRateOffense: 0.14,
        tdDriveRateDefense: 0.22,
        turnoverDriveRateOffense: 0.18,
        turnoverDriveRateDefense: 0.08,
        thirdDownEfficiencyOffense: 0.35,
        thirdDownEfficiencyDefense: 0.48,
        penaltiesOffensive: 7,
        penaltiesDefensive: 3,
      },
    },
    {
      id: "game-3",
      week: weekNumber,
      homeTeam: teams.PHI,
      awayTeam: teams.DEN,
      status: "scheduled",
      gameTime: "1:00 PM ET",
      homeMetrics: {
        epaOffensePercentile: 0,
        epaOffenseValue: 0,
        epaDefensePercentile: 0,
        epaDefenseValue: 0,
        passNeutralRate: 0,
        scoringDriveRateOffense: 0,
        scoringDriveRateDefense: 0,
        tdDriveRateOffense: 0,
        tdDriveRateDefense: 0,
        turnoverDriveRateOffense: 0,
        turnoverDriveRateDefense: 0,
        thirdDownEfficiencyOffense: 0,
        thirdDownEfficiencyDefense: 0,
        penaltiesOffensive: 0,
        penaltiesDefensive: 0,
      },
      awayMetrics: {
        epaOffensePercentile: 0,
        epaOffenseValue: 0,
        epaDefensePercentile: 0,
        epaDefenseValue: 0,
        passNeutralRate: 0,
        scoringDriveRateOffense: 0,
        scoringDriveRateDefense: 0,
        tdDriveRateOffense: 0,
        tdDriveRateDefense: 0,
        turnoverDriveRateOffense: 0,
        turnoverDriveRateDefense: 0,
        thirdDownEfficiencyOffense: 0,
        thirdDownEfficiencyDefense: 0,
        penaltiesOffensive: 0,
        penaltiesDefensive: 0,
      },
    },
  ];

  return {
    weekNumber,
    startDate: `2026-01-${5 + weekNumber * 7}`,
    endDate: `2026-01-${11 + weekNumber * 7}`,
    games,
  };
}
